language: go

go:
  - 1.x

cache:
  directories:
    - $HOME/cache

install:
  - echo "Nothing to do"

before_script:
  - source ./scripts/commonEnv.bash
  - source ./scripts/setupEnv.bash
  - ./scripts/protobufInstall.sh

script:
  - ./scripts/runTests.sh
